repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.270"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        exclude: |
          (?x)^(
              src/web/*|
              _templates
          )$
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.0
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.16.5
    hooks:
      - id: slotscheck
        exclude: "test_*|docs|migrations"
        entry: env PYTHONPATH=src slotscheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        args: [--python-version=3.11]
        additional_dependencies:
          [
            pydantic,
            pylint-pydantic,
            jinja2,
            aiosql,
            uvloop,
            hiredis,
            passlib,
            rich,
            packaging,
            click,
            rich-click,
            polyfactory,
            structlog,
            aiosmtplib,
            alembic,
            asyncpg,
            asyncpg-stubs,
            httpx,
            pytest,
            pytest-docker,
            saq,
            https://github.com/litestar-org/litestar/archive/refs/heads/main.zip,
            types-freezegun,
            types-python-jose,
            types-click,
            types-redis,
            types-passlib,
            types-click,
            types-PyYAML,
            uvicorn,
          ]
