version: "3.3"
x-development-volumes: &development-volumes
  volumes:
    - ./docs:/workspace/app/docs/
    - ./tests:/workspace/app/tests/
    - ./src:/workspace/app/src/
    - ./Makefile:/workspace/app/Makefile
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./poetry.lock:/workspace/app/poetry.lock
    - ./mkdocs.yml:/workspace/app/mkdocs.yml
    - ./tsconfig.json:/workspace/app/tsconfig.json
    - ./package.json:/workspace/app/package.json
    - ./vite.config.ts:/workspace/app/vite.config.ts
services:
  localmail:
    image: mailhog/mailhog:v1.0.0
    container_name: localmail
    ports:
      - "8025"
  sprintlog:
    tty: true
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
      args:
        # remove this to build for production.
        POETRY_INSTALL_ARGS: --with=dev
    image: sprintlog:latest-dev
    command: litestar run --reload --host 0.0.0.0 --port 8000
    restart: "no"
    <<: *development-volumes
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env.example
  migrator:
    image: sprintlog:latest-dev
    command: litestar database upgrade --no-prompt
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  localcdn:
    image: sigoden/dufs
    ports:
      - 8866:5000
    volumes:
      - ./static:/data
    command: /data -A --enable-cors  --render-index
