version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postrgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: example-pg-docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build:
      context: .
      args:
        INSTALL_DEPENDENCIES: dev
    depends_on:
      mailhog:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy

    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:cached

volumes:
  db: {}
  cache: {}
