version: "3.9"
services:
  redis:
    image: redis:latest
    volumes:
      - cache:/data

  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postrgresql/data/
    ports:
      - "54326:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: example-pg-docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 3s

  app:
    build:
      context: .
      args:
        INSTALL_DEPENDENCIES: dev
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

    ports:
      - "8090:8000"
    env_file:
      - .env
    volumes:
      - .:/app:cached

volumes:
  db: {}
  cache: {}
