"""empty message

Revision ID: 3be59d796e98
Revises: ae9e9e3e60a9
Create Date: 2023-04-16 19:10:51.461691

"""
import sqlalchemy as sa
from alembic import op

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "3be59d796e98"
down_revision = "ae9e9e3e60a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("description", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "description")
    # ### end Alembic commands ###
