"""updated project fk

Revision ID: 5c446d1f99d9
Revises: 5d172b990858
Create Date: 2023-04-16 18:06:00.451202

"""
import sqlalchemy as sa
from alembic import op

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "5c446d1f99d9"
down_revision = "5d172b990858"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("project_slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.add_column("task", sa.Column("project_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f("fk_task_project_id_project"), "task", "project", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_task_project_id_project"), "task", type_="foreignkey")
    op.drop_column("task", "project_id")
    op.drop_table("project")
    # ### end Alembic commands ###
