"""updated project relationships

Revision ID: 5d172b990858
Revises: dafa56d026f8
Create Date: 2023-04-16 17:10:43.800293

"""
import sqlalchemy as sa
from alembic import op

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "5d172b990858"
down_revision = "dafa56d026f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "project_slug")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("project_slug", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
