"""slug_audit

Revision ID: 81e0c4151751
Revises: adff94f407f4
Create Date: 2023-05-10 17:56:55.390258

"""
import litestar
import sqlalchemy as sa
from alembic import op

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "81e0c4151751"
down_revision = "adff94f407f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("backlog", sa.Column("project_id", litestar.contrib.sqlalchemy.types.GUID(), nullable=False))
    op.add_column("backlog", sa.Column("_sentinel", sa.Integer(), nullable=True))
    op.drop_constraint("fk_backlog_project_slug_project", "backlog", type_="foreignkey")
    op.create_foreign_key(op.f("fk_backlog_project_id_project"), "backlog", "project", ["project_id"], ["id"])
    op.drop_column("backlog", "project_slug")
    op.add_column("backlog_audit", sa.Column("_sentinel", sa.Integer(), nullable=True))
    op.add_column("project", sa.Column("_sentinel", sa.Integer(), nullable=True))
    op.add_column("role", sa.Column("_sentinel", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("_sentinel", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "_sentinel")
    op.drop_column("role", "_sentinel")
    op.drop_column("project", "_sentinel")
    op.drop_column("backlog_audit", "_sentinel")
    op.add_column("backlog", sa.Column("project_slug", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("fk_backlog_project_id_project"), "backlog", type_="foreignkey")
    op.create_foreign_key("fk_backlog_project_slug_project", "backlog", "project", ["project_slug"], ["slug"])
    op.drop_column("backlog", "_sentinel")
    op.drop_column("backlog", "project_id")
    # ### end Alembic commands ###
