"""Added tags.

Revision ID: 89c08d0b6f6b
Revises: f254a0293c2a
Create Date: 2023-04-07 17:18:01.565008
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "89c08d0b6f6b"
down_revision = "f254a0293c2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("is_backlog", sa.Boolean(), nullable=False))
    op.add_column("task", sa.Column("tags", sa.ARRAY(sa.String()), nullable=False))
    op.drop_column("task", "is_closed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("is_closed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("task", "tags")
    op.drop_column("task", "is_backlog")
    # ### end Alembic commands ###
