"""updated role to list of strings

Revision ID: 96f22acccb3e
Revises: 5c446d1f99d9
Create Date: 2023-04-16 18:54:05.547270

"""
import sqlalchemy as sa
from alembic import op

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "96f22acccb3e"
down_revision = "5c446d1f99d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
