"""Tag_lable_optional.

Revision ID: a1ae9f360adf
Revises: 89c08d0b6f6b
Create Date: 2023-04-07 17:30:28.474214
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a1ae9f360adf"
down_revision = "89c08d0b6f6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "labels", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    op.alter_column(
        "task", "tags", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "tags", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    op.alter_column(
        "task", "labels", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    # ### end Alembic commands ###
