"""removed userrole association

Revision ID: ae9e9e3e60a9
Revises: 96f22acccb3e
Create Date: 2023-04-16 18:56:57.504276

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "ae9e9e3e60a9"
down_revision = "96f22acccb3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userrole")
    op.add_column("user", sa.Column("roles", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "roles")
    op.create_table(
        "userrole",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name="fk_userrole_role_id_role"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_userrole_user_id_user"),
        sa.PrimaryKeyConstraint("id", name="pk_userrole"),
    )
    # ### end Alembic commands ###
