"""added projects

Revision ID: dafa56d026f8
Revises: 0c47d166cac2
Create Date: 2023-04-16 16:50:07.092626

"""
import sqlalchemy as sa
from alembic import op

__all__ = ["downgrade", "upgrade"]


# revision identifiers, used by Alembic.
revision = "dafa56d026f8"
down_revision = "0c47d166cac2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("assignee_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f("fk_task_assignee_id_user"), "task", "user", ["assignee_id"], ["id"])
    op.drop_column("task", "assigned_to")
    op.drop_column("task", "assigned_by")
    op.add_column("user", sa.Column("email", sa.String(length=320), nullable=False))
    op.add_column("user", sa.Column("password_hash", sa.String(length=1024), nullable=False))
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    op.drop_column("user", "login_count")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("login_count", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_active")
    op.drop_column("user", "password_hash")
    op.drop_column("user", "email")
    op.add_column("task", sa.Column("assigned_by", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("task", sa.Column("assigned_to", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("fk_task_assignee_id_user"), "task", type_="foreignkey")
    op.drop_column("task", "assignee_id")
    # ### end Alembic commands ###
