"""project_owner

Revision ID: ef719e5e8eec
Revises: d59790eca890
Create Date: 2023-06-22 18:35:43.867066

"""
import sqlalchemy as sa
from alembic import op
from litestar.contrib.sqlalchemy.types import GUID, DateTimeUTC

__all__ = ["downgrade", "upgrade"]


sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
# revision identifiers, used by Alembic.
revision = "ef719e5e8eec"
down_revision = "d59790eca890"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("owner_id", sa.GUID(length=16), nullable=True))
    op.create_foreign_key(op.f("fk_project_owner_id_user_account"), "project", "user_account", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_project_owner_id_user_account"), "project", type_="foreignkey")
    op.drop_column("project", "owner_id")
    # ### end Alembic commands ###
