"""initial

Revision ID: 13b6784a4aa7
Revises:
Create Date: 2023-06-30 13:04:18.449918

"""
import sqlalchemy as sa
from alembic import op
from litestar.contrib.sqlalchemy.types import GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy.dialects import postgresql

__all__ = ["downgrade", "upgrade"]


sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB

# revision identifiers, used by Alembic.
revision = "13b6784a4aa7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
        comment="Tags that can be applied to various objects",
    )
    op.create_table(
        "team",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
    )
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=False)
    op.create_index(op.f("ix_team_slug"), "team", ["slug"], unique=True)
    op.create_table(
        "user_account",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name=op.f("uq_user_account_email")),
        comment="User accounts for application access",
    )
    op.create_table(
        "project",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("pin", sa.Boolean(), nullable=False),
        sa.Column("labels", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("documents", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("sprint_weeks", sa.Integer(), nullable=True),
        sa.Column("sprint_amount", sa.Integer(), nullable=True),
        sa.Column("sprint_checkup_day", sa.Integer(), nullable=True),
        sa.Column("repo_urls", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "plugin_meta",
            sa.JSON()
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.GUID(length=16), nullable=True),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user_account.id"], name=op.f("fk_project_owner_id_user_account")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("slug", name=op.f("uq_project_slug")),
    )
    op.create_table(
        "team_invitation",
        sa.Column("team_id", sa.GUID(length=16), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_accepted", sa.Boolean(), nullable=False),
        sa.Column("invited_by_id", sa.GUID(length=16), nullable=True),
        sa.Column("invited_by_email", sa.String(), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["user_account.id"],
            name=op.f("fk_team_invitation_invited_by_id_user_account"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_team_invitation_team_id_team"), ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_invitation")),
    )
    op.create_index(op.f("ix_team_invitation_email"), "team_invitation", ["email"], unique=False)
    op.create_table(
        "team_member",
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("team_id", sa.GUID(length=16), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("fk_team_member_team_id_team"), ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.id"], name=op.f("fk_team_member_user_id_user_account"), ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_member")),
        sa.UniqueConstraint("user_id", "team_id", name=op.f("uq_team_member_user_id")),
    )
    op.create_index(op.f("ix_team_member_role"), "team_member", ["role"], unique=False)
    op.create_table(
        "team_tag",
        sa.Column("team_id", sa.GUID(length=16), nullable=False),
        sa.Column("tag_id", sa.GUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], name=op.f("fk_team_tag_tag_id_tag"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("fk_team_tag_team_id_team"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "tag_id", name=op.f("pk_team_tag")),
    )
    op.create_table(
        "backlog",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("progress", sa.String(length=50), nullable=False),
        sa.Column("sprint_number", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("est_days", sa.Float(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("beg_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("labels", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "plugin_meta",
            sa.JSON()
            .with_variant(sa.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.GUID(length=16), nullable=True),
        sa.Column("owner_id", sa.GUID(length=16), nullable=True),
        sa.Column("project_slug", sa.String(), nullable=True),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assignee_id"], ["user_account.id"], name=op.f("fk_backlog_assignee_id_user_account")),
        sa.ForeignKeyConstraint(["owner_id"], ["user_account.id"], name=op.f("fk_backlog_owner_id_user_account")),
        sa.ForeignKeyConstraint(["project_slug"], ["project.slug"], name=op.f("fk_backlog_project_slug_project")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backlog")),
    )
    op.create_index(op.f("ix_backlog_category"), "backlog", ["category"], unique=False)
    op.create_index(op.f("ix_backlog_priority"), "backlog", ["priority"], unique=False)
    op.create_index(op.f("ix_backlog_progress"), "backlog", ["progress"], unique=False)
    op.create_index(op.f("ix_backlog_slug"), "backlog", ["slug"], unique=True)
    op.create_index(op.f("ix_backlog_status"), "backlog", ["status"], unique=False)
    op.create_index(op.f("ix_backlog_title"), "backlog", ["title"], unique=False)
    op.create_index(op.f("ix_backlog_type"), "backlog", ["type"], unique=False)
    op.create_table(
        "backlog_audit",
        sa.Column("backlog_id", sa.GUID(length=16), nullable=False),
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("old_value", sa.String(), nullable=False),
        sa.Column("new_value", sa.String(), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["backlog_id"], ["backlog.id"], name=op.f("fk_backlog_audit_backlog_id_backlog")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backlog_audit")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backlog_audit")
    op.drop_index(op.f("ix_backlog_type"), table_name="backlog")
    op.drop_index(op.f("ix_backlog_title"), table_name="backlog")
    op.drop_index(op.f("ix_backlog_status"), table_name="backlog")
    op.drop_index(op.f("ix_backlog_slug"), table_name="backlog")
    op.drop_index(op.f("ix_backlog_progress"), table_name="backlog")
    op.drop_index(op.f("ix_backlog_priority"), table_name="backlog")
    op.drop_index(op.f("ix_backlog_category"), table_name="backlog")
    op.drop_table("backlog")
    op.drop_table("team_tag")
    op.drop_index(op.f("ix_team_member_role"), table_name="team_member")
    op.drop_table("team_member")
    op.drop_index(op.f("ix_team_invitation_email"), table_name="team_invitation")
    op.drop_table("team_invitation")
    op.drop_table("project")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_team_slug"), table_name="team")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_table("team")
    op.drop_table("tag")
    # ### end Alembic commands ###
