"""get backlog by slug

Revision ID: b0c3d687d336
Revises: b7569b018e1d
Create Date: 2023-05-20 23:57:32.749186

"""
import sqlalchemy as sa
from alembic import op
from litestar.contrib.sqlalchemy.types import GUID, JSON

__all__ = ["downgrade", "upgrade"]


sa.GUID = GUID
sa.JSON = JSON

# revision identifiers, used by Alembic.
revision = "b0c3d687d336"
down_revision = "b7569b018e1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("documents", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "documents")
    # ### end Alembic commands ###
