"""backlog_slug_nullable

Revision ID: b7569b018e1d
Revises: 302754c3712d
Create Date: 2023-05-20 18:45:27.514067

"""
import sqlalchemy as sa
from alembic import op
from litestar.contrib.sqlalchemy.types import GUID, JSON

__all__ = ["downgrade", "upgrade"]


sa.GUID = GUID
sa.JSON = JSON

# revision identifiers, used by Alembic.
revision = "b7569b018e1d"
down_revision = "302754c3712d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("backlog", sa.Column("slug", sa.String(), nullable=True))
    op.create_unique_constraint(op.f("uq_backlog_slug"), "backlog", ["slug"])
    op.drop_column("backlog", "ref_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("backlog", sa.Column("ref_id", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("uq_backlog_slug"), "backlog", type_="unique")
    op.drop_column("backlog", "slug")
    # ### end Alembic commands ###
