PROJECT_LIST = "/api/projects"
PROJECT_DETAIL = "/api/projects/{id:uuid}"
PROJECT_UPDATE = "/api/projects/{id:uuid}"
PROJECT_STATUS_UP = "/api/projects/status/up/{id:uuid}"
PROJECT_STATUS_DOWN = "/api/projects/status/down/{id:uuid}"
PROJECT_DELETE = "/api/projects/{id:uuid}"
PROJECT_CREATE = "/api/projects/create"
PROJECT_DETAIL_BY_SLUG = "/api/projects/{slug:str}"
