# type: ignore
"""added a new model 'chat'

Revision ID: d2129609493d
Revises: 7bf332fd4544
Create Date: 2025-04-16 08:42:49.540108+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = 'd2129609493d'
down_revision = '7bf332fd4544'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('parent_id', sa.GUID(length=16), nullable=True),
    sa.Column('sprint_id', sa.GUID(length=16), nullable=False),
    sa.Column('chat_type', postgresql.ENUM('MESSAGE', 'ANNOUNCEMENT', 'NOTE', 'GROUP', 'DIRECT', 'CHANNEL', name='chattype'), nullable=False),
    sa.Column('event_type', postgresql.ENUM('CREATED', 'UPDATED', 'DELETED', 'JOINED', 'LEFT', 'ARCHIVED', 'UNARCHIVED', 'PINNED', 'UNPINNED', 'MENTIONED', 'REACTED', 'UNREACTED', 'SHARED', 'UNSHARED', name='eventtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['chats.id'], name=op.f('fk_chats_parent_id_chats')),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint_log.id'], name=op.f('fk_chats_sprint_id_sprint_log')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
