# type: ignore
"""added new fields for the latest litestar-fullstack

Revision ID: e1cd658b634d
Revises: 3437165a44f6
Create Date: 2025-03-27 05:09:29.509041+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = 'e1cd658b634d'
down_revision = '3437165a44f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
        batch_op.drop_column('_sentinel')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('ix_project_slug_unique', ['slug'], unique=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.create_index('ix_tag_slug_unique', ['slug'], unique=True)
        batch_op.create_unique_constraint('uq_tag_slug', ['slug'])
        batch_op.drop_table_comment(
        existing_comment='Tags that can be applied to various objects'
    )

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('ix_team_slug')
        batch_op.create_index('ix_team_slug_unique', ['slug'], unique=True)
        batch_op.create_unique_constraint('uq_team_slug', ['slug'])

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_user_account_email', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_account_email'), ['email'], unique=True)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_email'))
        batch_op.create_unique_constraint('uq_user_account_email', ['email'])
        batch_op.drop_column('login_count')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_slug', type_='unique')
        batch_op.drop_index('ix_team_slug_unique')
        batch_op.create_index('ix_team_slug', ['slug'], unique=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tags that can be applied to various objects',
        existing_comment=None
    )
        batch_op.drop_constraint('uq_tag_slug', type_='unique')
        batch_op.drop_index('ix_tag_slug_unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_slug_unique')

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_sentinel', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('sa_orm_sentinel')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
