# type: ignore
"""added new fields is_archived and status to th project model

Revision ID: 22d3bf17999f
Revises: c69fc7eca072
Create Date: 2025-03-29 09:59:42.957013+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "22d3bf17999f"
down_revision = "c69fc7eca072"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    with op.batch_alter_table("project", schema=None) as batch_op:
        # Temporarily allow NULL for safe upgrade
        batch_op.add_column(sa.Column("status", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("is_archived", sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f("ix_project_status"), ["status"], unique=False)
    op.execute("UPDATE project SET status = 'not-started' WHERE status IS NULL;")
    op.execute("UPDATE project SET is_archived = FALSE WHERE is_archived IS NULL;")

    # Now that defaults are set, alter columns to be NOT NULL
    op.alter_column("project", "status", existing_type=sa.String(length=50), nullable=False)
    op.alter_column("project", "is_archived", existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_status"))
        batch_op.drop_column("is_archived")
        batch_op.drop_column("status")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""
    # Set default values for existing rows before enforcing NOT NULL


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
