# type: ignore
"""added bankAccount model and 1-to-Many relationship with user_account"

Revision ID: c69fc7eca072
Revises: a62993d5e879
Create Date: 2025-03-28 03:22:00.772904+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = 'c69fc7eca072'
down_revision = 'a62993d5e879'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_bank_account_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_account'))
    )
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_method'), ['method'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tag_slug', ['slug'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_slug', ['slug'])

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('position')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_slug', type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tag_slug', type_='unique')

    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_method'))

    op.drop_table('bank_account')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
